version: "2.2"
services:
  desktop:
    container_name: automation-desktop
    build:
      context: ./
      dockerfile: Dockerfile
    image: oseongryu/automation-desktop:1.0.0
    ports:
      - "13389:3389"
      - "13000:3000"
      - "18091:8091"
    volumes:
      - ~/git:/git
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
    privileged: true
