version: "2.2"
services:
  desktop:
    container_name: automation-desktop
    build:
      context: ./desktop/
      dockerfile: Dockerfile
    image: oseongryu/automation-desktop:1.0.0
    ports:
      - "13389:3389"
      - "3000:3000"
      - "8091:8091"
    volumes:
      - ~/git:/git
      - /c/app:/app
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
    privileged: true
