version: "3.1"

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: testdb
      MARIADB_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
