version: "2.2"
services:
  desktop:
    container_name: automation-desktop
    build:
      context: ./desktop/
      dockerfile: Dockerfile
    image: oseongryu/automation-desktop:1.0.0
    ports:
      - "13389:3389"
      - "3000:3000"
      - "8080:8080"
      - "8091:8091"
    volumes:
      - ~/git:/git
      - /c/app:/app
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
    privileged: true
  mariadb:
    container_name: db-mariadb
    image: mysql:5.7
    restart: always
    # 컨테이너에서 사용하는 volume 설정으로 대체 가능(옵션)
    # volumes:
    #   - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASES=mydb
    stdin_open: true # docker run -i
    tty: true # docker run -t
    ports:
      - "3306:3306"
    privileged: true
    # # 컨테이너 간 네트워크 분리를 위한 추가 설정 부분(옵션)
    # network:
